### PR TITLE
checking nanotime

### PR DESCRIPTION
**Pull request by edhartnett**
Part of #4.

With this PR we now correctly set HAVE_NANOTIME.

### CODE REVIEW

**Comment by edhartnett** [comment]
Looks like you have required in GitHub that at least one approving review is required. So you need to open the review and hit approve so that you can then merge this PR.

**Comment by edhartnett** [comment]
It is not me that needs to approve. In fact, I don't have that button. Take a look here:
https://help.github.com/articles/about-pull-request-reviews/

**Comment by jmrosinski** [comment]
Something appears to be hosed. I've hit "approve" and "submit" multiple
times with no response from the system as to why a merge is not possible.
Can we just disable review requirements until this gets sorted out? Maybe
the problem is I don't work for NOAA any more? Are you the repo owner or am
I?

**Comment by edhartnett** [comment]
Don't panic, we can solve it. ;-)

Change my permissions to admin and I will take a look...

**Comment by jmrosinski** [comment]
Not sure if this is the problem or not, but when I click on  my icon I DO
show up as owner of GPTL, but NOT the owner of GPTL-fortran. Could this be
the problem? How does one find out the owner of a particular repository?

**Comment by edhartnett** [comment]
Oh, duh! My fault. Stand by...

**Pull request merged**
